# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
     config.vm.box = "ubuntu/bionic64"
     config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
     config.vm.synced_folder ".", "/vagrant"


     config.vm.provision "docker"

# provider Settings
    config.vm.provider "virtualbox" do |vb|
       vb.name = "Ubuntu-vm"
       vb.gui = false
       vb.memory = "2048"
    end
end

