# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
     config.vm.box = "ubuntu/bionic64"
     config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
     config.vm.synced_folder ".", "/vagrant"

     config.vm.provision "shell", path: "docker_installation.sh"
     config.vm.provision "docker" do |d|
       d.pull_images "gracegoma/wordpress"
       d.pull_images "gracegoma/mysql"
       d.run "wordpress", image: "gracegoma/wordpress",
           args: "-p 80:8080/tcp -p 443:443/tcp"
       d.run "mysql", image: "gracegoma/mysql"
    end

# provider Settings
    config.vm.provider "virtualbox" do |vb|
       vb.name = "Ubuntu-vm"
       vb.gui = false
       vb.memory = "2048"
    end
end

